---
abstract: 'Role to clone attribute values from one class into another'
author:
  - 'Andy Brown <setitesuk@gmail.com>'
build_requires:
  JSON: 0
  MooseX::InsideOut: 0
  Test::Exception: 0
  Test::More: 0.8
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: lgpl3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-AttributeCloner
provides:
  MooseX::AttributeCloner:
    file: lib/MooseX/AttributeCloner.pm
    version: 0.19
requires:
  Carp: 1.04
  English: 1.02
  JSON: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Getopt: 0
  MooseX::InsideOut: 0
  Readonly: 1.03
  Test::Exception: 0
  Test::More: 0.74
resources:
  license: http://opensource.org/licenses/lgpl-3.0.html
version: 0.19
