---
name: MooseX-AttributeCloner
version: 0.14
author:
  - 'Andy Brown <setitesuk@gmail.com>'
abstract: Role to clone attribute values from one class into another
license: lgpl3
resources:
  license: http://www.gnu.org/licenses/lgpl-3.0.txt
requires:
  Carp: 1.04
  English: 1.02
  JSON: 0
  Moose: 0
  Moose::Role: 0
  MooseX::InsideOut: 0
  Readonly: 1.03
  Test::Exception: 0
  Test::More: 0.74
build_requires:
  JSON: 0
  MooseX::InsideOut: 0
  Test::Exception: 0
  Test::More: 0.8
provides:
  MooseX::AttributeCloner:
    file: lib/MooseX/AttributeCloner.pm
    version: 0.14
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
